### PR TITLE
cluster: detect in-container docker and fix KIND kubeconfig

### LINKED ISSUE #251: setting up a kind cluster with docker mounted in docker
From the tilt slack channel:

> When ctlptl applies the new cluster, it can never connect because the kubeconfig IP is set incorrectly. So it waits 5 minutes then bails. Our one working solution is to use KIND directly to create the cluster, modify the kubeconfig to point at a working IP, and then use the cluster... but then I have to write shell scripts to manage the cluster and attached temporary registry. So it would be ideal if I could use ctlptl.

I think they're using docker-socket-mounted-in-docker, which means that the cluster and registry will be in sibling containers, but the networking won't be set up right. ctlptl should detect this case and patch up the networking, similar to how we do it when there's a remote docker host.

### PR DESCRIPTION
**Pull request by nicksieger**
When ctlptl is run in a container, fix the KIND kubeconfig so ctlptl and other
containers can reach the apiserver on the kind network.

Fixes #251.

Signed-off-by: Nick Sieger <nick@nicksieger.com>

### CODE REVIEW

**Comment by nicksieger** [comment]
Still getting some differences in cluster detection.

```shell
# Local
$ ctlptl get cluster -o yaml
apiVersion: ctlptl.dev/v1alpha1
items:
- apiVersion: ctlptl.dev/v1alpha1
  kind: Cluster
  name: kind-kind
  product: kind
  registry: kind-registry
  status:
    cpus: 5
    creationTimestamp: "2022-09-13T21:06:41Z"
    current: true
    kubernetesVersion: v1.25.0
    localRegistryHosting:
      help: https://github.com/tilt-dev/ctlptl
      host: localhost:39423
      hostFromClusterNetwork: kind-registry:5000
kind: ClusterList
# Container
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v kubeconfig:/root/.kube docker/tilt-ctlptl ctlptl get cluster -o yaml
apiVersion: ctlptl.dev/v1alpha1
items:
- apiVersion: ctlptl.dev/v1alpha1
  kind: Cluster
  name: kind-kind
  product: kind
  status:
    creationTimestamp: null
    current: true
kind: ClusterList
```

File: pkg/cluster/cluster.go [hunk 1]
```diff
@@ -1108,3 +1114,49 @@ func (c *Controller) waitForHealthCheckAfterCreate(ctx context.Context, cluster
...
+	if cluster.Product != string(clusterid.ProductKIND) {
+		return nil
+	}
+
+	if c.dockerClient.DaemonHost() != "unix:///var/run/docker.sock" {
+		return nil
+	}
+
+	if inContainer, err := strconv.ParseBool(
+		strings.TrimSpace(os.Getenv("CTLPTL_IN_CONTAINER")),
```
Comment (nicks) [inline pkg/cluster/cluster.go:1136]: i think this is fine for now, but i do wonder if there's a better way to detect if we're running under the same docker instance we're connected to.

File: pkg/cluster/cluster.go [hunk 2]
```diff
@@ -1108,3 +1114,49 @@ func (c *Controller) waitForHealthCheckAfterCreate(ctx context.Context, cluster
...
+	); err != nil || !inContainer {
+		return nil
+	}
+
+	hostName, err := os.Hostname()
+	if err != nil {
+		return fmt.Errorf("could not determine container host name: %w", err)
+	}
+
+	err = c.dockerClient.NetworkConnect(ctx, kindNetworkName(), hostName, nil)
```
Comment (nicks) [inline pkg/cluster/cluster.go:1146]: can we make this a method on the `Admin` interface? maybe 

```
func (a *Admin) DockerNetworkName()
```

there's nothing here that really seems specific to `kind`, seems like this approach would work on minikube and k3d too (though i think it's ok to punt on minikube and k3d for now)

File: pkg/cluster/cluster.go [hunk 3]
```diff
@@ -1108,3 +1114,49 @@ func (c *Controller) waitForHealthCheckAfterCreate(ctx context.Context, cluster
...
+	if err != nil {
+		if !strings.Contains(err.Error(), "already exists in network") {
```
Comment (nicks) [inline pkg/cluster/cluster.go:1148]: really surprising to me that this is a forbidden error rather than a NotModifiedError

**Review by nicks — APPROVED** [review]
nice! left some minor comments

File: pkg/cluster/cluster.go (hunk 1 above)
Comment (nicks) [reply pkg/cluster/cluster.go:1136]: maybe we could check if /etc/hostname looks like a container id, and ContainerInspect() says that container id is running?

File: pkg/cluster/cluster.go (hunk 3 above)
Comment (nicksieger) [reply pkg/cluster/cluster.go:1148]: Yeah, I was considering changing this to use `errdefs.IsForbidden` but it looks like I'll still need to filter by message in order to ignore the specific case where the endpoint already exists.

**Review by nicks — APPROVED** [review]
